Alert
Veekshith-Thoram/spud-ui pull request #2
Opened 2022-03-17 03:12 UTC by Veekshith-Thoram

![image](https://user-images.githubusercontent.com/67872770/158729015-06689e91-9ab7-4627-b3f0-2b5e14ffc95c.png)

2022-03-17 03:47 UTC, AtulPant2704 commented on alert/alert.css
> +}
You should have all of these colors in utility.css, not inside alert.css as you would need these colors at various pages.

2022-03-17 03:48 UTC, AtulPant2704 commented on alert/alert.css
> +    --yellow: #f59e0b;
Try to give names to the colors according to their use-case, not according to their color.

2022-03-17 03:49 UTC, AtulPant2704 commented on alert/alert.css
> +    /* margin-left: 10%; */
You can remove this comment.

2022-03-17 03:52 UTC, AtulPant2704 requested changes
There is so much commented code in your PR, remove all of those comments and extract out your colors in a separate file.

2022-03-17 04:46 UTC, AnkurChunekar requested changes

2022-03-17 04:46 UTC, AnkurChunekar commented on alert/alert.css
> +    /* margin-top: 1rem; */
Remove unnecessary comments.

2022-03-17 04:46 UTC, AnkurChunekar commented on alert/alert.css
> +}
add a last line at the end of the file to avoid getting this error

2022-03-26 10:38 UTC, Artistole approved these changes

2022-03-26 10:38 UTC, merged