Avatar
Veekshith-Thoram/spud-ui pull request #3
Opened 2022-03-17 03:14 UTC by Veekshith-Thoram

![image](https://user-images.githubusercontent.com/67872770/158729427-fac2c123-b875-43eb-8d4a-21976073976d.png)

2022-03-17 03:55 UTC, AtulPant2704 commented on homepage/main.css
> +    /* background-color: var(--primary-color); */
Remove this comment.

2022-03-17 03:56 UTC, AtulPant2704 commented on homepage/main.css
> +    --secondary-color: ;
You have not assigned any color to this variable, I think this will result in an error.

2022-03-17 03:57 UTC, AtulPant2704 commented on avatar/avatar.css
> +    /* margin-top: 3rem; */
Remove this comment as well.

2022-03-17 03:59 UTC, AtulPant2704 commented on avatar/avatar.css
> +    list-style: none;
This you could have done in your reset.css file itself, you could have given `ul` `list-style: none` over there and then imported that file in all the files where you wanted to use that, you don't need to write an explicit class just for that.

2022-03-17 04:05 UTC, AtulPant2704 requested changes
- You have included `alert.html` in this branch, from next time onwards try to have files specific to that branch in that PR.
- Remove all the unnecessary comments.
- Assign a color to the `secondary-color` or remove that line itself if it is of no use.
- From next PR, only have screenshot of the UI page itself, not of the code. We are gonna review the code anyway.

2022-03-17 04:54 UTC, AnkurChunekar requested changes

2022-03-17 04:54 UTC, AnkurChunekar commented on avatar/avatar.css
> +
Please try to be consistent in line spacing and indentation.

2022-03-17 04:54 UTC, AnkurChunekar commented on avatar/avatar.html
> +                    style="width: 70%; height: 125px;" frameborder="0"></iframe>
Avoid inline styling wherever possible.

2022-03-17 04:54 UTC, AnkurChunekar commented on avatar/avatar.html
> +                <div class="text-container">
Here also indentation and spacing is inconsistent, use a code formatter. I use prettier that might help.

2022-03-26 10:27 UTC, Artistole approved these changes

2022-03-26 10:34 UTC, merged